# Generated by Django 2.0.6 on 2019-10-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_file',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
