# Generated by Django 2.0.6 on 2019-10-15 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0004_auto_20191015_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='img_file',
            new_name='image',
        ),
    ]
