# Generated by Django 2.0.6 on 2019-10-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0006_auto_20191015_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article',
            new_name='content',
        ),
    ]
