# Generated by Django 2.0.6 on 2019-10-15 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0007_auto_20191015_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
