# Generated by Django 2.0.6 on 2019-10-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0011_auto_20191016_1916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageFile',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
