# Generated by Django 2.0.6 on 2019-10-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0012_auto_20191016_2346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllWiki',
        ),
        migrations.AddField(
            model_name='relatedarticle',
            name='related_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
