# Generated by Django 2.0.6 on 2019-10-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0013_auto_20191017_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedarticle',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
